site_name: CS492(C) Diffusion and Flow Models (KAIST, Fall 2025)
site_url: https://diffusion.kaist.ac.kr/
site_author: Minhyuk Sung

theme:
  name: material
  icon:
    logo: material/cube-outline
  features:
    - navigation.tabs
    - navigation.tabs.sticky

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - footnotes
  - meta
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables

plugins:
  - macros

copyright: Copyright &copy; 2025 Minhyuk Sung

nav:
  - Home: index.md
  - Programming Assignments: programming-assignments.md
  - In-Class Tests: in-class-tests.md
  - Image Generation Challenge: image-generation-challenge.md
  - Visual Generation Contest: visual-generation-contest.md
  - Guest Lecture 1: guest-lecture-subham-sahoo.md
#  - Guest Lecture 2: guest-lecture-jiaming-song.md

extra:
  analytics:
    provider: google
    property: G-B8SSD5F8FW
  links:
    lec01: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VkOFQzMzF6allkUHZTTElRRnpqRkM4QlF3Y2FOZkM5MVBtNTRlcnZJUk1fbWc%5FZT1yc0tjTlQ&cid=60562023B6640282&id=60562023B6640282%21s7ddf13df8d734f87bd22c8405ce3142f&parId=60562023B6640282%21s1f04e32a613643ea8f3a45539dc2c1ff&o=OneUp
    lec02: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VURGlxMktycFhKT254S2VqU3BfRl80Qkw0UkVUWWd6Rm4tb2xvTjB5U2ctM0E%5FZT1ZT2JJWGI&cid=60562023B6640282&id=60562023B6640282%21s62abe230a5ab4e729f129e8d2a7f17fe&parId=60562023B6640282%21s1f04e32a613643ea8f3a45539dc2c1ff&o=OneUp
    lec03: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VVeUJaUnFfRTl4THI2YXcyQVhvb3NBQmVFMXgtenNwbW8ycUF5aXUzNkZETXc%5FZT1jZzZ0YWI&cid=60562023B6640282&id=60562023B6640282%21s1a65814c13bf4bdcafa6b0d805e8a2c0&parId=60562023B6640282%21s1f04e32a613643ea8f3a45539dc2c1ff&o=OneUp
    lec04: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VZSUZhelJLbXVKSWxLeUx6dDBCZWZzQk55MG1obHhxS0RwYUFUdkFyODF3UWc%5FZT1FMHRNU0E&cid=60562023B6640282&id=60562023B6640282%21s346b05829a4a48e294ac8bcedd0179fb&parId=60562023B6640282%21s1f04e32a613643ea8f3a45539dc2c1ff&o=OneUp
    lec05: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VYRmI2eWVGdHBaSG9BR2N5NUZhbVI4QjZtbWJxbXdIbEt0M2t6dGdCaElaYnc%5FZT1Qc3FzNmE&cid=60562023B6640282&id=60562023B6640282%21s27eb5b71b6854796a0019ccb915a991f&parId=60562023B6640282%21s1f04e32a613643ea8f3a45539dc2c1ff&o=OneUp
    lec06: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VYd0RUWkhyeEdOTnJjYmYzSE02aGFJQnRIMXpjMEgwcDFpZ0lmXy1udUtfLWc%5FZT13MXhQbDc&cid=60562023B6640282&id=60562023B6640282%21s914d037cc4eb4d63adc6dfdc733a85a2&parId=60562023B6640282%21s1f04e32a613643ea8f3a45539dc2c1ff&o=OneUp
    lec07: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VXMkR0enVCdXY5TWdNZWNVSkc2VUhFQjAzMHQyRDdINThTNDZYeDlaQW1zekE%5FZT1LZXNVRjc&cid=60562023B6640282&id=60562023B6640282%21s3bb7836dba814cff80c79c5091ba5071&parId=60562023B6640282%21s1f04e32a613643ea8f3a45539dc2c1ff&o=OneUp
    lec08: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VRRzlCUU5XTE45T2d1YmdLVHROWTFZQlpVMkZ0NVM5MUduSDJQTUVQT3lpM3c%5FZT1iajRMUHE&cid=60562023B6640282&id=60562023B6640282%21s0305bd012c564edf82e6e0293b4d6356&parId=60562023B6640282%21s1f04e32a613643ea8f3a45539dc2c1ff&o=OneUp
    lec09: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VUbXFIQ0dOcUNSTWdzZlk3RWpCMjRnQldBcHN4U2NaMlBPTkluOGV6QnUxRUE%5FZT1jRk5VYmU&cid=60562023B6640282&id=60562023B6640282%21s211caa39a88d4c2482c7d8ec48c1db88&parId=60562023B6640282%21s1f04e32a613643ea8f3a45539dc2c1ff&o=OneUp
    lec10: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0ViRFJ4b0ZDMWo1R2pzbkk5cy1EUko4Qk5uQzNWR1lDdmFVejdxcnJQS0U3bEE%5FZT1kbTdrcHQ&cid=60562023B6640282&id=60562023B6640282%21s81c6d1b0d642463e8ec9c8f6cf83449f&parId=60562023B6640282%21s1f04e32a613643ea8f3a45539dc2c1ff&o=OneUp
    lec11: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VXd3VBTzVodU1sSm80blAtYnF4RXNvQnJ4Y2tQaGNBVWxTOVlGay03RGlIaVE%5FZT1OTjZ5SVo&cid=60562023B6640282&id=60562023B6640282%21see002e6cb86149c9a389cff9bab112ca&parId=60562023B6640282%21s1f04e32a613643ea8f3a45539dc2c1ff&o=OneUp
    asgmt01: https://github.com/KAIST-Visual-AI-Group/Diffusion-2025-Assignment1-DDPM-DDIM
    asgmt02: https://github.com/KAIST-Visual-AI-Group/Diffusion-2025-Assignment2-DPMSolver
    asgmt03: https://github.com/KAIST-Visual-AI-Group/Diffusion-2025-Assignment3-Flow
    demo: https://github.com/KAIST-Visual-AI-Group/Diffusion-2025-Demo
    image_gen_repo: https://github.com/KAIST-Visual-AI-Group/Diffusion-2025-Image_Challenge
    imgge_gen_slides: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VmZWFKeVdLaVRGSGp4RWc3dkRSeEpNQjdTekhLMnpQNmtpVVlBQ3JtaFRONHc%5FZT1lRXhxR0Q&cid=60562023B6640282&id=60562023B6640282%21s25279af7898a47318f1120eef0d1c493&parId=60562023B6640282%21s5f0abf9bf9a34d9d9e25be0a166b01d3&o=OneUp
    visual_gen_slides: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VScW5zWmhzOU5KTHRxT3FGWnE3S3RJQjJKMnBxQ0EzbVVmUF9nS3VoNVpOWGc%5FZT1tY1hUY2s&cid=60562023B6640282&id=60562023B6640282%21s98b1a71af46c4bd2b6a3aa159abb2ad2&parId=60562023B6640282%21s5f0abf9bf9a34d9d9e25be0a166b01d3&o=OneUp
    rec02: https://youtu.be/96XoVM7PYtQ
    rec03: https://youtu.be/qiFZQvcqTOo
    rec04: https://youtu.be/5_t3uSvdrWg
    rec05: https://youtu.be/AG4qcza52yo
    rec06: https://youtu.be/vRvT1NOKsxw
    rec07: https://youtu.be/elW_X0ezM70
    rec08: https://youtu.be/by_flhcQJj4
    rec09: https://youtu.be/eKW5AAy5ae8
    rec10: https://youtu.be/-1hgQC58Nfc
    rec11: https://youtu.be/o9tccBWdcQ4
    colab: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VTRzBSUTEwZFFkSHNHWllsT1FJNUxrQnZaX1RheGppTHphcUxXSzBsb0JtOHc%5FZT1uOFlucFI&cid=60562023B6640282&id=60562023B6640282%21s0d45b42175744707b0665894e408e4b9&parId=60562023B6640282%21s5f0abf9bf9a34d9d9e25be0a166b01d3&o=OneUp
    sess01: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VTNUZiN0RTWWlWRmt5WEdYQWVwZzJRQkRaSlNOb1drY3pDa1gza2NpTXdnRFE%5FZT1OUGRkRkE&cid=60562023B6640282&id=60562023B6640282%21sb06f452e62d245259325c65c07a98364&parId=60562023B6640282%21s5f0abf9bf9a34d9d9e25be0a166b01d3&o=OneUp
    sess02: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VTOEdaSjZSZHZ0RHJwNFJNVGIxZmo0QkZ6NVRGT196b2l0ejI2QXpfbjRhRFE%5FZT1iMkVKb3U&cid=60562023B6640282&id=60562023B6640282%21s9e64062f769143fbae9e113136f57e3e&parId=60562023B6640282%21s5f0abf9bf9a34d9d9e25be0a166b01d3&o=OneUp
    sess03: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0VWak5UdTJmVVVOSGd1bkV3WHpucFc4Qm1PcEhiajE1d2JkdjBqenI2c2JOUXc%5FZT1TSW1iS0Q&cid=60562023B6640282&id=60562023B6640282%21sed4ecd58519f474382e9c4c17ce7a56f&parId=60562023B6640282%21s5f0abf9bf9a34d9d9e25be0a166b01d3&o=OneUp
    templates: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL3UvYy82MDU2MjAyM2I2NjQwMjgyL0VRWjVLUncyMWFwR2s0UXRIS0xPeXFvQkcyQ2NEbmlHb09XY1diUlF0VmpyMHc%5FZT1oVUFucXE&cid=60562023B6640282&id=60562023B6640282%21s1c297906d53646aa93842d1ca2cecaaa&parId=60562023B6640282%21s78c041bd29af458f9c22a3ecb87bb3be&o=OneUp
    zoom: https://kaist.zoom.us/j/88406148948
